2025-09-13 22:26:35,018 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/sql_keyword.yaml
2025-09-13 22:26:35,045 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/sql_keyword.yaml
2025-09-13 22:26:35,045 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/xml_parser_config.yaml
2025-09-13 22:26:35,051 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/xml_parser_config.yaml
2025-09-13 22:26:35,052 - SourceAnalyzer - DEBUG - logger.py:64 - 파일 읽기 성공: config/parser/mybatis_dom_rules.yaml
2025-09-13 22:26:35,053 - SourceAnalyzer - DEBUG - logger.py:64 - YAML 설정 파일 로드 성공: config/parser/mybatis_dom_rules.yaml
2025-09-13 22:26:35,057 - SourceAnalyzer - INFO - logger.py:68 - DOM 기반 파싱 시도: .\projects\sampleSrc\src\com\example\dynamicquery\UserMapper.xml
2025-09-13 22:26:35,062 - SourceAnalyzer - ERROR - logger.py:128 - FATAL ERROR at D:\Analyzer\CreateMetaDb\parser\xml_parser.py:163 in extract_sql_queries_and_analyze_relationships()
Code: dom_result = self._parse_with_dom(xml_file)
Message: XML 파일 분석 중 치명적 오류 발생: .\projects\sampleSrc\src\com\example\dynamicquery\UserMapper.xml
Exception: TypeError: XmlParser._parse_with_dom() missing 1 required positional argument: 'file_path'
Stack Trace:
Traceback (most recent call last):
  File "D:\Analyzer\CreateMetaDb\parser\xml_parser.py", line 163, in extract_sql_queries_and_analyze_relationships
    dom_result = self._parse_with_dom(xml_file)
TypeError: XmlParser._parse_with_dom() missing 1 required positional argument: 'file_path'

